pipeline{
    agent any
    stages{
        stage('Clean'){
            steps{
                echo "Clean Stage"
                batch "mvn clean"
            }
        }
        stage('Test'){
            steps{
                echo "Test Stage"
                batch "mvn test"
            }
        }
        stage('Package'){
            steps{
                echo "Package Stage"
                batch "mvn package"
            }
        }
        stage('Deploy'){
            steps{
                echo "Deploy Stage"
                batch "mvn deploy"
            }
        }
    }
}
